sudo: required
language: php
dist: trusty

php:
- 7.3

addons:
  chrome: stable

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install sqlite3

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - nvm install 10.15.3
  - npm install npm@6.4.1
  - npm cache clear --force
  - npm install
  - php artisan key:generate

before_script:
  - touch database/physistrong.sqlite
  - php artisan ziggy:generate "resources/js/zroutes.js"
  - npm run development
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.testing .env
  - php artisan serve &

script:
  - php artisan dusk
  - vendor/bin/phpcs
  - vendor/bin/phpunit
  - npm run test
