sudo: required
language: php
dist: trusty

php:
- 7.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install sqlite3

install:
  - travis_retry composer install --no-interaction

before_script:
  - touch database/physistrong.sqlite
  - cp .env.testing .env

script:
    - vendor/bin/phpcs
    - vendor/bin/phpunit
