sudo: required
language: php
dist: trusty

php:
- 7.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install sqlite3

install:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan jwt:secret
  - npm install
  - npm run dev

before_script:
  - touch database/physistrong.sqlite
  - cp .env.testing .env

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit